/**
 * This file was generated by the JPA Modeler
 */
package joke.hfad.com.miudelar.data.api.model;

import java.io.Serializable;
import java.util.List;
import java.util.Objects;

public class DtCarrera implements Serializable {

    private Long codigo;

    private String nombre;

    private List<DtAsignatura_Carrera> asignatura_Carreras;

    private List<DtPeriodo_Examen> periodos_Examenes;

    private List<DtAsignatura> asignaturas;

    public DtCarrera(Long codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }

    public DtCarrera() {
    }

    public Long getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public List<DtAsignatura_Carrera> getAsignatura_Carreras() {
        return this.asignatura_Carreras;
    }

    public void setAsignatura_Carreras(List<DtAsignatura_Carrera> asignatura_Carreras) {
        this.asignatura_Carreras = asignatura_Carreras;
    }

    public List<DtPeriodo_Examen> getPeriodos_Examenes() {
        return this.periodos_Examenes;
    }

    public void setPeriodos_Examenes(List<DtPeriodo_Examen> periodos_Examenes) {
        this.periodos_Examenes = periodos_Examenes;
    }

    public List<DtAsignatura> getAsignaturas() {
        return this.asignaturas;
    }

    public void setAsignaturas(List<DtAsignatura> asignaturas) {
        this.asignaturas = asignaturas;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.codigo);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final DtCarrera other = (DtCarrera) obj;
        if (!Objects.equals(this.codigo, other.codigo)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return Long.toString(codigo) + " - " + nombre;
    }
}
