/**
 * This file was generated by the JPA Modeler
 */
package joke.hfad.com.miudelar.data.api.model;

import java.io.Serializable;
import java.util.List;
import java.util.Objects;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class DtUsuario implements Serializable {

    private String cedula;

    private String nombre;

    private String apellido;

    private String email;

    private String password;

    private List<DtEstudiante_Examen> calificacionesExamenes;

    private List<DtEstudiante_Curso> calificacionesCursos;

    private List<DtRol> roles;

    private List<DtCarrera> carreras;

    private List<DtExamen> inscripcionesExamenes;

    private List<DtCurso> cursos;

    public DtUsuario(String cedula, String nombre, String apellido, String email, String password, List<DtRol> roles) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.apellido = apellido;
        this.email = email;
        this.password = password;
        this.roles = roles;
    }
    
 
    public DtUsuario(String cedula, String nombre, String apellido, String email, String password) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.apellido = apellido;
        this.email = email;
        this.password = password;
    }

    public DtUsuario() {
    }

    public String getCedula() {
        return this.cedula;
    }

    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public List<DtEstudiante_Examen> getCalificacionesExamenes() {
        return this.calificacionesExamenes;
    }

    public void setCalificacionesExamenes(List<DtEstudiante_Examen> calificacionesExamenes) {
        this.calificacionesExamenes = calificacionesExamenes;
    }

    public List<DtEstudiante_Curso> getCalificacionesCursos() {
        return this.calificacionesCursos;
    }

    public void setCalificacionesCursos(List<DtEstudiante_Curso> calificacionesCursos) {
        this.calificacionesCursos = calificacionesCursos;
    }

    public List<DtRol> getRoles() {
        return this.roles;
    }

    public void setRoles(List<DtRol> roles) {
        this.roles = roles;
    }

    public List<DtCarrera> getCarreras() {
        return this.carreras;
    }

    public void setCarreras(List<DtCarrera> carreras) {
        this.carreras = carreras;
    }

    public List<DtExamen> getInscripcionesExamenes() {
        return this.inscripcionesExamenes;
    }

    public void setInscripcionesExamenes(List<DtExamen> inscripcionesExamenes) {
        this.inscripcionesExamenes = inscripcionesExamenes;
    }

    public List<DtCurso> getCursos() {
        return this.cursos;
    }

    public void setCursos(List<DtCurso> cursos) {
        this.cursos = cursos;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 47 * hash + Objects.hashCode(this.cedula);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final DtUsuario other = (DtUsuario) obj;
        if (!Objects.equals(this.cedula, other.cedula)) {
            return false;
        }
        return true;
    }
  
}
